name = input("What is your name: ")
coun = input("What country are you from: ")
age = input("How old are you? ")
dre_ca = input("What is your dream career? ")
print("----- Profile -----")
print("Name: ", name)
print("Country: ", coun)
print("Age: ", age)
print("Dream career: ", dre_ca)